<?php
declare(strict_types=1);

const CONFIG_FILE = __DIR__ . '/config.local.php';

function app_is_installed(): bool {
    return file_exists(CONFIG_FILE);
}

function db_config(): array {
    if (!app_is_installed()) {
        return [];
    }
    return require CONFIG_FILE;
}

function get_pdo(): PDO {
    static $pdo = null;
    if ($pdo instanceof PDO) {
        return $pdo;
    }
    $config = db_config();
    if (!$config) {
        throw new RuntimeException('Application is not configured yet.');
    }
    $dsn = sprintf(
        'mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4',
        $config['host'],
        $config['port'],
        $config['name']
    );
    $pdo = new PDO($dsn, $config['user'], $config['pass'], [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ]);
    return $pdo;
}

/**
 * Connect without selecting a database, used by the installer to test
 * credentials and create the target database if it does not exist yet.
 */
function get_server_pdo(string $host, int $port, string $user, string $pass): PDO {
    $dsn = sprintf('mysql:host=%s;port=%d;charset=utf8mb4', $host, $port);
    return new PDO($dsn, $user, $pass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ]);
}

function write_db_config(string $host, int $port, string $name, string $user, string $pass): void {
    $contents = "<?php\n// Generated by the PalmPocket installer. Do not commit this file.\nreturn [\n"
        . "    'host' => " . var_export($host, true) . ",\n"
        . "    'port' => " . var_export($port, true) . ",\n"
        . "    'name' => " . var_export($name, true) . ",\n"
        . "    'user' => " . var_export($user, true) . ",\n"
        . "    'pass' => " . var_export($pass, true) . ",\n"
        . "];\n";
    if (file_put_contents(CONFIG_FILE, $contents, LOCK_EX) === false) {
        throw new RuntimeException('Could not write config.local.php. Check folder permissions.');
    }
}
